#!/bin/bash
# Fast sync is valid only for the same inputs AND actual generated bytes.
# Fixtures stay outside the checkout so project discovery cannot select it.
set -euo pipefail
unset CI
REPO="${1:-$(cd "$(dirname "$0")/../.." && pwd)}"
REPO="$(cd "$REPO" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/runtime" "$TMP/project with spaces/intelligence/rules"
cp -R "$REPO/cli" "$REPO/engine" "$TMP/runtime/"
CLI="$TMP/runtime/cli/intelligence"
PROJECT="$TMP/project with spaces"
STATE="$PROJECT/.intelligence/sync-cache/state"
mkdir "$TMP/instrumentation"
for command in bash cp find; do
    {
        printf '#!/bin/bash\nLOG=%q\nREAL=%q\nPROJECT=%q\n' "$TMP/operations" "$(command -v "$command")" "$PROJECT"
        case "$command" in
            bash) cat <<'WRAPPER'
case "${1:-}" in */engine/sync.sh) echo engine >> "$LOG" ;; esac
WRAPPER
                ;;
            cp) cat <<'WRAPPER'
for arg in "$@"; do
    case "$arg" in */intelligence-sync-*/data/*) echo snapshot >> "$LOG" ;; esac
done
WRAPPER
                ;;
            find) cat <<'WRAPPER'
for arg in "$@"; do
    [ "$arg" != "$PROJECT" ] || echo discovery >> "$LOG"
    if [ -e "$LOG.fail-find" ] && [ "$arg" = "$PROJECT/intelligence/skills" ]; then
        printf '%s\n' "$PROJECT/intelligence/skills/demo"
        exit 1
    fi
done
WRAPPER
                ;;
        esac
        printf 'exec "$REAL" "$@"\n'
    } > "$TMP/instrumentation/$command"
    chmod +x "$TMP/instrumentation/$command"
done
export PATH="$TMP/instrumentation:$PATH"
VERSION="$(tr -d ' \r\n' < "$REPO/engine/VERSION")"
OUTPUT=""; RC=0; checks=0
fail() { printf 'FAIL: %s\n%s\n' "$1" "$OUTPUT" >&2; exit 1; }
check() { checks=$((checks + 1)); "$@" || fail "$*"; }
has() { grep -qF -- "$1" <<< "$OUTPUT"; }
lacks() { ! has "$1"; }
run() {
    RC=0
    OUTPUT="$(cd "$PROJECT" && bash "$CLI" sync "$@" 2>&1)" || RC=$?
}
miss() { run "$@"; check test "$RC" -eq 0; check lacks 'Unchanged: verified'; }
hit() { run "$@"; check test "$RC" -eq 0; check has 'Unchanged: verified'; }
cat > "$PROJECT/intelligence.yaml" <<EOF
schema_version: "$VERSION"
project:
  name: cache-test
sources:
  rules:
    - intelligence/rules
  agents:
    - intelligence/agents
  skills:
    - intelligence/skills
targets:
  agents:
    enabled: true
    output: AGENTS.md
  claude:
    enabled: true
    output: .claude
  codex:
    enabled: true
    output: .codex
  copilot:
    enabled: true
    output: .github
  cursor:
    enabled: true
    output: .cursor
  pi:
    enabled: true
    output: .pi
EOF
mkdir -p "$PROJECT/intelligence/agents" "$PROJECT/intelligence/skills/demo/assets"
printf '%s\n' '---' 'description: Local rule' '---' 'Alpha' > "$PROJECT/intelligence/rules/base.md"
printf '%s\n' '---' 'description: A skill' '---' '# Demo' > "$PROJECT/intelligence/skills/demo/SKILL.md"
printf '\000\001\377binary\000' > "$PROJECT/intelligence/skills/demo/assets/data.bin"
printf '%s\n' '---' 'description: A reviewer' 'tier: standard' 'access: readonly' '---' '# Review' > "$PROJECT/intelligence/agents/review.md"

echo '== Multiline native adapter warnings retain their actionable continuation =='
(
    source "$REPO/engine/lib/common.sh"
    source "$REPO/engine/lib/adapter-contract.sh"
    source "$REPO/engine/adapters/antigravity.sh"
    source "$REPO/cli/lib/sync-cache.sh"
    mkdir -p "$TMP/warning-fixture/.agents/rules"
    antigravity_warn_unread_output "$TMP/warning-fixture" "$TMP/warning-fixture/.elsewhere" > "$TMP/warning-log" 2>&1
    printf '  rule: renderer progress\n' >> "$TMP/warning-log"
    sync_cache_report "$TMP/warning-log" > "$TMP/warning-report"
)
check grep -q '^WARNING: Antigravity' "$TMP/warning-report"
check grep -q 'stale copy is what Antigravity loads. Remove it' "$TMP/warning-report"
check test "$(wc -l < "$TMP/warning-report" | tr -d ' ')" -eq 2

echo '== Six built-ins, first/full sync and unchanged bytes/mtimes =='
miss
check test -f "$STATE"
cp "$PROJECT/AGENTS.md" "$TMP/expected"
touch -t 200201010000 "$TMP/marker"
find "$PROJECT/.agents" "$PROJECT/.claude" "$PROJECT/.codex" "$PROJECT/.github" "$PROJECT/.cursor" "$PROJECT/.pi" "$PROJECT/AGENTS.md" -type f -exec touch -t 200101010000 {} +
: > "$TMP/operations"
hit
check test ! -s "$TMP/operations"
check cmp "$TMP/expected" "$PROJECT/AGENTS.md"
changed="$(find "$PROJECT/.agents" "$PROJECT/.claude" "$PROJECT/.codex" "$PROJECT/.github" "$PROJECT/.cursor" "$PROJECT/.pi" "$PROJECT/AGENTS.md" -type f -newer "$TMP/marker")"
check test -z "$changed"
check has 'IS_STATUS=ok IS_DETAIL=synced=6'
check has '=== Done: 6 target(s) synced ==='

echo '== Compact hit, force, and target-filter isolation =='
run --compact
check test "$RC" -eq 0
check lacks 'Unchanged:'
check has 'CONTEXT:'
check has 'IS_STATUS=ok'
check test "$(grep -Ec '^(WARNING:|CONTEXT:|IS_STATUS=ok|=== Done:)' <<< "$OUTPUT")" -eq "$(wc -l <<< "$OUTPUT" | tr -d ' ')"
miss --force
check grep -qx engine "$TMP/operations"
check grep -qx snapshot "$TMP/operations"
check grep -qx discovery "$TMP/operations"
hit
miss --compact --force
miss agents
hit agents
miss
hit
run missing
check test "$RC" -ne 0
check test ! -f "$STATE"
miss

echo '== Failed fingerprint enumeration cannot reuse a primed success cache =='
cp "$PROJECT/AGENTS.md" "$TMP/enumeration-before"
: > "$TMP/operations"
: > "$TMP/operations.fail-find"
run
check test "$RC" -ne 0
check lacks 'Unchanged: verified'
check lacks 'IS_STATUS=ok'
check has 'cannot enumerate skills'
check grep -qx engine "$TMP/operations"
check cmp "$TMP/enumeration-before" "$PROJECT/AGENTS.md"
rm "$TMP/operations.fail-find"
hit

# The remaining mutation matrix needs a shared skill destination, an owned
# rules destination and a later failing adapter, not all six renderers again.
awk '/^  (pi|cursor|copilot):$/ { disable=1 }
    disable && /^    enabled:/ { sub(/true/, "false"); disable=0 }
    { print }' "$PROJECT/intelligence.yaml" > "$TMP/fewer-targets"
cp "$TMP/fewer-targets" "$PROJECT/intelligence.yaml"
miss

echo '== Same-size source edit with preserved mtime =='
cp -p "$PROJECT/intelligence/rules/base.md" "$TMP/rule-before"
sed 's/Alpha/Bravo/' "$TMP/rule-before" > "$PROJECT/intelligence/rules/base.md"
touch -r "$TMP/rule-before" "$PROJECT/intelligence/rules/base.md"
miss
check grep -q Bravo "$PROJECT/AGENTS.md"
hit

echo '== Rule/agent changes and special resource names =='
printf '\nChanged agent\n' >> "$PROJECT/intelligence/agents/review.md"
miss
check grep -q 'Changed agent' "$PROJECT/.codex/agents/review.toml"
printf '# New rule\n' > "$PROJECT/intelligence/rules/new.md"
miss
mv "$PROJECT/intelligence/rules/new.md" "$PROJECT/intelligence/rules/renamed.md"
miss
check test ! -e "$PROJECT/.claude/rules/new.md"
rm "$PROJECT/intelligence/rules/renamed.md"
miss
printf resource > "$PROJECT/intelligence/skills/demo/assets/café [1] & space.txt"
miss
check cmp "$PROJECT/intelligence/skills/demo/assets/café [1] & space.txt" "$PROJECT/.agents/skills/demo/assets/café [1] & space.txt"

echo '== Binary resources, file add/rename/delete and empty directories =='
printf '\000\002\377binary\000' > "$PROJECT/intelligence/skills/demo/assets/data.bin"
miss
check cmp "$PROJECT/intelligence/skills/demo/assets/data.bin" "$PROJECT/.agents/skills/demo/assets/data.bin"
printf resource > "$PROJECT/intelligence/skills/demo/assets/with space.txt"
miss
mv "$PROJECT/intelligence/skills/demo/assets/with space.txt" "$PROJECT/intelligence/skills/demo/assets/renamed.txt"
miss
check test ! -e "$PROJECT/.agents/skills/demo/assets/with space.txt"
rm "$PROJECT/intelligence/skills/demo/assets/renamed.txt"
miss
mkdir "$PROJECT/intelligence/skills/demo/assets/empty"
miss
rmdir "$PROJECT/intelligence/skills/demo/assets/empty"
miss
hit

echo '== Source executable mode, when the host exposes it =='
printf '#!/bin/sh\nexit 0\n' > "$PROJECT/intelligence/skills/demo/assets/tool"
chmod -x "$PROJECT/intelligence/skills/demo/assets/tool"
miss
if [ ! -x "$PROJECT/intelligence/skills/demo/assets/tool" ]; then
    chmod +x "$PROJECT/intelligence/skills/demo/assets/tool"
    miss
else
    echo 'SKIP executable-bit transition: filesystem reports every file executable'
fi

echo '== Missing/edited output, owned-directory additions and preserved siblings =='
rm "$PROJECT/AGENTS.md"
miss
check test -f "$PROJECT/AGENTS.md"
printf damaged >> "$PROJECT/.agents/skills/demo/assets/data.bin"
miss
check cmp "$PROJECT/intelligence/skills/demo/assets/data.bin" "$PROJECT/.agents/skills/demo/assets/data.bin"
printf authored > "$PROJECT/.claude/settings.local.json"
hit
check grep -qx authored "$PROJECT/.claude/settings.local.json"
printf extra > "$PROJECT/.claude/rules/unexpected.md"
miss
check test ! -f "$PROJECT/.claude/rules/unexpected.md"
check grep -qx authored "$PROJECT/.claude/settings.local.json"

echo '== Manifest and installed runtime invalidation =='
printf '\n# changed manifest\n' >> "$PROJECT/intelligence.yaml"
miss
printf '\n# changed runtime\n' >> "$TMP/runtime/engine/lib/common.sh"
miss
printf '\n# changed CLI\n' >> "$TMP/runtime/cli/lib/sync-cache.sh"
miss
hit
cp "$TMP/runtime/engine/VERSION" "$TMP/version-before"
printf '0.1.0\n' > "$TMP/runtime/engine/VERSION"
miss
check has 'WARNING: project schema'
cp "$TMP/version-before" "$TMP/runtime/engine/VERSION"
miss
hit

echo '== Layout/output changes and actionable warning replay =='
cp "$PROJECT/intelligence.yaml" "$TMP/layout-before"
sed 's/output: .claude/output: .claude-other/' "$TMP/layout-before" > "$PROJECT/intelligence.yaml"
miss
check test -f "$PROJECT/.claude-other/rules/base.md"
cp "$TMP/layout-before" "$PROJECT/intelligence.yaml"
miss
awk '{ print; if ($0 == "  codex:") print "    warn_project_doc_limit: 1" }' "$TMP/layout-before" > "$PROJECT/intelligence.yaml"
miss
check has 'WARNING: Codex may truncate'
hit
check has 'WARNING: Codex may truncate'
run --compact
check test "$RC" -eq 0
check has 'WARNING: Codex may truncate'
cp "$TMP/layout-before" "$PROJECT/intelligence.yaml"
printf '%s\n' '---' 'description: Unquoted: colon' '---' 'Lint warning' > "$PROJECT/intelligence/rules/warning.md"
miss
check has 'unquoted colon'
hit
check has 'unquoted colon'
rm "$PROJECT/intelligence/rules/warning.md"
miss

echo '== Discovery is refreshed on miss/force; useful warnings survive hits =='
mkdir -p "$PROJECT/apps/one/intelligence/rules"
printf '# Unconfigured\n' > "$PROJECT/apps/one/intelligence/rules/test.md"
hit
check lacks 'NOT SYNCED: apps/one'
miss --force
check has 'NOT SYNCED: apps/one/intelligence/rules'
hit
check has 'NOT SYNCED: apps/one/intelligence/rules'
mkdir -p "$PROJECT/apps/two/intelligence/rules"
printf '# Unconfigured\n' > "$PROJECT/apps/two/intelligence/rules/test.md"
hit
check lacks 'NOT SYNCED: apps/two'
printf '\nChanged\n' >> "$PROJECT/intelligence/rules/base.md"
miss
check has 'NOT SYNCED: apps/two/intelligence/rules'

echo '== Missing, malformed and partial cache safely fall back =='
rm "$STATE"
miss
printf '$(touch should-never-execute)\n' > "$STATE"
miss
check test ! -e "$PROJECT/should-never-execute"
printf 'corrupted report\n' >> "$STATE"
miss
head -n 1 "$STATE" > "$TMP/partial"
cp "$TMP/partial" "$STATE"
miss
hit

echo '== Failure preserves exit status, rolls output back and cannot cache success =='
cp "$PROJECT/intelligence.yaml" "$TMP/manifest"
cp "$PROJECT/AGENTS.md" "$TMP/rollback"
printf '\nNew content\n' >> "$PROJECT/intelligence/rules/base.md"
awk '{ print; if ($0 == "  codex:") print "    warn_project_doc_limit: 0" }' "$TMP/manifest" > "$PROJECT/intelligence.yaml"
run --compact
check test "$RC" -eq 1
check has 'restored to their pre-sync state'
check cmp "$TMP/rollback" "$PROJECT/AGENTS.md"
check test ! -f "$STATE"
cp "$TMP/manifest" "$PROJECT/intelligence.yaml"
miss
hit
printf 'packages: [broken\n' > "$PROJECT/intelligence.lock"
run
check test "$RC" -ne 0
check has 'invalid intelligence.lock'
rm "$PROJECT/intelligence.lock"
hit

echo '== Changes during rendering are never blessed as current output =='
cp "$TMP/runtime/engine/sync.sh" "$TMP/sync-before"
printf '\nprintf "\\nConcurrent change\\n" >> "$REPO_ROOT/intelligence/rules/base.md"\n' >> "$TMP/runtime/engine/sync.sh"
miss
check test ! -f "$STATE"
cp "$TMP/sync-before" "$TMP/runtime/engine/sync.sh"
miss
hit

echo '== Project adapters have unknown dependencies and always render =='
mkdir -p "$PROJECT/intelligence/adapters"
cat > "$PROJECT/intelligence/adapters/extra.sh" <<'ADAPTER'
adapter_contract_extra() { adapter_contract_version 1; adapter_contract_owned extra.txt; }
sync_to_extra() { printf custom > "$1/extra.txt"; }
ADAPTER
printf '\n  extra:\n    enabled: true\n    output: extra.txt\n' >> "$PROJECT/intelligence.yaml"
miss
miss
check test -f "$PROJECT/extra.txt"
rm "$PROJECT/intelligence/adapters/extra.sh"
cp "$TMP/manifest" "$PROJECT/intelligence.yaml"
miss
hit

echo '== Link fallback and cache-path containment, when links are available =='
mkdir "$TMP/external"
printf external > "$TMP/external/file"
if MSYS=winsymlinks:nativestrict ln -s "$TMP/external/file" "$PROJECT/intelligence/skills/demo/assets/link" 2>/dev/null && [ -L "$PROJECT/intelligence/skills/demo/assets/link" ]; then
    miss
    miss
    rm "$PROJECT/intelligence/skills/demo/assets/link"
    miss
    rm -rf "$PROJECT/.intelligence/sync-cache"
    MSYS=winsymlinks:nativestrict ln -s "$TMP/external" "$PROJECT/.intelligence/sync-cache"
    miss
    miss
    check test ! -e "$TMP/external/state"
    rm "$PROJECT/.intelligence/sync-cache"
    miss
    hit
else
    rm -f "$PROJECT/intelligence/skills/demo/assets/link"
    echo 'SKIP symlink cases: host cannot create native symlinks'
fi

echo '== Windows junction ancestors must not authorize cache reads/writes =='
if command -v cmd.exe >/dev/null 2>&1 && command -v cygpath >/dev/null 2>&1; then
    rm -rf "$PROJECT/.intelligence/sync-cache"
    junction="$(cygpath -w "$PROJECT/.intelligence/sync-cache")"
    destination="$(cygpath -w "$TMP/external")"
    printf '@echo off\r\nmklink /J "%s" "%s"\r\n' "$junction" "$destination" > "$TMP/junction.cmd"
    MSYS_NO_PATHCONV=1 cmd.exe /d /c "$(cygpath -w "$TMP/junction.cmd")" > "$TMP/junction-log" 2>&1
    check test -L "$PROJECT/.intelligence/sync-cache"
    miss
    check test ! -e "$TMP/external/state"
    rm "$PROJECT/.intelligence/sync-cache"
    miss
    hit
else
    echo 'SKIP Windows junction case: non-Windows host'
fi

echo '== Installed bundled content stays offline on misses and hits =='
ORIGINAL_PROJECT="$PROJECT"
mkdir -p "$TMP/runtime/packages" "$TMP/offline" "$TMP/bin"
cp -R "$REPO/packages/sync" "$TMP/runtime/packages/sync"
PROJECT="$TMP/offline"
OUTPUT="$(cd "$PROJECT" && bash "$CLI" init --targets agents --no-sync 2>&1)" || fail 'offline init'
REAL_GIT="$(command -v git)"
cat > "$TMP/bin/git" <<EOF
#!/bin/bash
case "\$1" in clone|fetch|ls-remote) echo 'forbidden network acquisition' >&2; exit 91 ;; esac
exec "$REAL_GIT" "\$@"
EOF
chmod +x "$TMP/bin/git"
ORIGINAL_PATH="$PATH"
export PATH="$TMP/bin:$PATH"
miss
hit
package_rule="$(find "$PROJECT/.intelligence/packages" -type f -name '*.md')"
package_rule="${package_rule%%$'\n'*}"
check test -n "$package_rule"
printf '\nChanged local package\n' >> "$package_rule"
miss
hit
export PATH="$ORIGINAL_PATH"
PROJECT="$ORIGINAL_PROJECT"

echo '== Engine compatibility refusal still precedes cache =='
cp "$PROJECT/intelligence.yaml" "$TMP/manifest"
sed "s/schema_version: \"$VERSION\"/schema_version: \"99.0.0\"/" "$TMP/manifest" > "$PROJECT/intelligence.yaml"
run --compact
check test "$RC" -eq 4
check has 'IS_STATUS=ahead-of-engine'
cp "$TMP/manifest" "$PROJECT/intelligence.yaml"
hit
echo "== sync-cache: $checks checks passed =="
