#!/bin/bash
# Concurrent rendering (decision 0011) must be indistinguishable from the serial
# order in everything a run leaves behind: generated bytes, console text, exit
# status, and the restored state after a failure. Every case runs the same
# project twice, once with INTELLIGENCE_SYNC_SERIAL=1, and compares.
set -euo pipefail
unset CI INTELLIGENCE_SYNC_SERIAL
REPO="${1:-$(cd "$(dirname "$0")/../.." && pwd)}"
REPO="$(cd "$REPO" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/runtime"
cp -R "$REPO/cli" "$REPO/engine" "$TMP/runtime/"
CLI="$TMP/runtime/cli/intelligence"
VERSION="$(tr -d ' \r\n' < "$REPO/engine/VERSION")"
fail=0
checks=0
check() { checks=$((checks + 1)); if ! "$@"; then echo "FAIL: $*"; fail=1; fi; }

SEED="$TMP/seed"
mkdir -p "$SEED/intelligence/rules" "$SEED/intelligence/agents" "$SEED/intelligence/skills/demo/assets" \
    "$SEED/intelligence/skills/second"
cat > "$SEED/intelligence.yaml" <<EOF
schema_version: "$VERSION"
project:
  name: concurrency-test
sources:
  rules:
    - intelligence/rules
  agents:
    - intelligence/agents
  skills:
    - intelligence/skills
targets:
  agents:
    enabled: true
    output: AGENTS.md
  antigravity:
    enabled: true
    output: .agents
  claude:
    enabled: true
    output: .claude
  codex:
    enabled: true
    output: .codex
  copilot:
    enabled: true
    output: .github
  cursor:
    enabled: true
    output: .cursor
  opencode:
    enabled: true
    output: .opencode
  pi:
    enabled: true
    output: .pi
models:
  claude:
    heavy: "claude-opus-override"
EOF
printf '%s\n' '---' 'description: Always on' '---' '# Base' 'Always-on body' > "$SEED/intelligence/rules/base.md"
printf '%s\n' '---' 'description: Scoped' 'paths:' '  - "src/**"' '---' '# Scoped' 'Scoped body' > "$SEED/intelligence/rules/scoped.md"
printf '%s\n' '---' 'description: A reviewer' 'tier: standard' 'access: readonly' '---' '# Review' > "$SEED/intelligence/agents/review.md"
printf '%s\n' '---' 'description: A builder' 'tier: heavy' 'access: full' '---' '# Build' > "$SEED/intelligence/agents/build.md"
printf '%s\n' '---' 'name: demo' 'description: A skill' '---' '# Demo' > "$SEED/intelligence/skills/demo/SKILL.md"
printf '\000\001\377binary\000' > "$SEED/intelligence/skills/demo/assets/data.bin"
printf '%s\n' '---' 'name: second' 'description: Another skill' '---' '# Second' > "$SEED/intelligence/skills/second/SKILL.md"
mkdir -p "$SEED/.claude" && printf '{}\n' > "$SEED/.claude/settings.json"

# run <project> <serial:0|1> <args...> — sets OUT (paths normalized) and RC.
run() {
    local project="$1" serial="$2"
    shift 2
    RC=0
    if [ "$serial" = 1 ]; then
        OUT="$(cd "$project" && INTELLIGENCE_SYNC_SERIAL=1 bash "$CLI" sync "$@" 2>&1)" || RC=$?
    else
        OUT="$(cd "$project" && bash "$CLI" sync "$@" 2>&1)" || RC=$?
    fi
    OUT="$(printf '%s\n' "$OUT" | sed -e "s#$project#PROJECT#g" -e 's#intelligence-[a-z]*-[A-Za-z0-9]*#TMP#g')"
}

# same_run <label> <args...> — run the serial and concurrent copies, compare.
same_run() {
    local label="$1" serial_out serial_rc
    shift
    run "$TMP/serial" 1 "$@"
    serial_out="$OUT"; serial_rc="$RC"
    run "$TMP/concurrent" 0 "$@"
    check test "$RC" = "$serial_rc"
    if [ "$OUT" != "$serial_out" ]; then
        echo "FAIL: $label: console output differs"
        diff <(printf '%s\n' "$serial_out") <(printf '%s\n' "$OUT") | head -20
        fail=1
    fi
    if ! diff -r -x sync-cache "$TMP/serial" "$TMP/concurrent" > "$TMP/tree.diff" 2>&1; then
        echo "FAIL: $label: generated trees differ"
        head -20 "$TMP/tree.diff"
        fail=1
    fi
}

cp -R "$SEED" "$TMP/serial"
cp -R "$SEED" "$TMP/concurrent"

echo '== full render: same bytes and same console text =='
same_run "first sync" --force
check test "$RC" -eq 0
check test -f "$TMP/concurrent/AGENTS.md"
check test -f "$TMP/concurrent/.agents/skills/demo/assets/data.bin"
check test -f "$TMP/concurrent/.claude/settings.json"
same_run "second force" --force
same_run "compact" --force --compact
same_run "filtered" claude --force
same_run "filtered shared" codex --force

echo '== an adapter failure restores everything with the serial status and text =='
for side in serial concurrent; do
    awk '{ print; if ($0 == "  codex:") print "    warn_project_doc_limit: 0" }' \
        "$TMP/$side/intelligence.yaml" > "$TMP/manifest" && mv "$TMP/manifest" "$TMP/$side/intelligence.yaml"
done
cp -R "$TMP/concurrent" "$TMP/before-failure"
run "$TMP/serial" 1 --force
serial_rc="$RC"
serial_out="$OUT"
run "$TMP/concurrent" 0 --force
check test "$serial_rc" -ne 0
check test "$RC" = "$serial_rc"
check grep -qF 'warn_project_doc_limit must be true, false, or a positive byte count' <<< "$OUT"
check grep -qF 'restored to their pre-sync state' <<< "$OUT"
check test "$(tail -1 <<< "$OUT")" = "$(tail -1 <<< "$serial_out")"
if ! diff -r -x sync-cache "$TMP/before-failure" "$TMP/concurrent" > "$TMP/tree.diff" 2>&1; then
    echo "FAIL: a failed concurrent render left changes behind"
    head -20 "$TMP/tree.diff"
    fail=1
fi
for side in serial concurrent; do
    awk '$0 != "    warn_project_doc_limit: 0"' "$TMP/$side/intelligence.yaml" > "$TMP/manifest" \
        && mv "$TMP/manifest" "$TMP/$side/intelligence.yaml"
done
same_run "after the fix" --force
check test "$RC" -eq 0

echo '== a project adapter keeps the render serial and identical =='
for side in serial concurrent; do
    mkdir -p "$TMP/$side/intelligence/adapters"
    cat > "$TMP/$side/intelligence/adapters/myide.sh" <<'EOF'
adapter_contract_myide() {
    adapter_contract_version 1
    adapter_contract_owned "$1"
}
sync_to_myide() {
    echo "=== MyIDE ==="
    rm -rf "$3"
    mkdir -p "$3"
    [ -f "$1/AGENTS.md" ] && cp "$1/AGENTS.md" "$3/seen-agents.md"
    echo "  -> copied"
}
EOF
    printf '  myide:\n    enabled: true\n    output: .myide\n' > "$TMP/myide-target"
    awk -v add="$(cat "$TMP/myide-target")" '{ print } /^targets:$/ { print add }' \
        "$TMP/$side/intelligence.yaml" > "$TMP/manifest" && mv "$TMP/manifest" "$TMP/$side/intelligence.yaml"
done
same_run "project adapter" --force
check test "$RC" -eq 0
check cmp "$TMP/concurrent/AGENTS.md" "$TMP/concurrent/.myide/seen-agents.md"

[ "$fail" -eq 0 ] && echo "== concurrency: $checks checks passed =="
exit "$fail"
