#!/bin/bash
# intelligence-sync: opencode adapter
# Transforms source prompts to opencode's native resource model.
#
# Rules:
#   - Always-on (no `paths:`) -> SKIPPED here. opencode reads AGENTS.md
#     natively as its primary "Rules" surface (see opencode.ai/docs/rules).
#   - Path-scoped (with `paths:`) -> SKIPPED. opencode has no first-class
#     scoped-rule mechanism; users who want scoped rules can opt in via
#     `instructions:` globs in opencode.json. We do not synthesize that.
# Skills:
#   - Copied to .agents/skills/ (Agent Skills open standard; opencode
#     discovers `.agents/skills/<name>/SKILL.md` natively).
# Commands:
#   - For every synced skill, emit `.opencode/commands/<name>.md` so users can
#     invoke the skill as `/<name> [args]` directly from the slash menu —
#     replicating the Claude Code UX where every skill is also a slash
#     command. The command body delegates to the `skill` tool and forwards
#     `$ARGUMENTS` so any flags from the skill's `argument-hint` reach the
#     skill script unchanged. Cleanup is marker-based: only files containing
#     the generation marker are removed, so user-managed commands survive.
# Agents:
#   - Converted to .opencode/agents/<name>.md markdown agents
#     (mode: subagent) with frontmatter description/model/permission. The
#     body is the source agent's prompt, used directly as the system prompt.
#
# Every per-file loop batches its work into one awk process (see the batched
# helpers in lib/common.sh): process spawns dominate sync time on Windows.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

adapter_contract_opencode() {
    local output="${1%/}"
    adapter_contract_version 1
    adapter_contract_requires agents
    adapter_contract_managed ".agents/skills"
    adapter_contract_owned "$output/agents"
    adapter_contract_managed "$output/commands"
    adapter_contract_ignore ".agents/skills/"
    adapter_contract_ignore "$output/agents/"
}

sync_opencode_skills() {
    local repo_root="$1"
    local config_file="$2"
    local _output_dir="$3"

    # Skills -> .agents/skills/ (open standard; opencode reads it natively).
    # `sync_open_skill_dirs` owns clean + populate of this shared dir.
    local skills_dir="$repo_root/.agents/skills"
    sync_open_skill_dirs "$repo_root" "$config_file" "$skills_dir"
}

# Marker line embedded in every generated command file. Cleanup grep's for
# this exact string before deleting, so any user-authored command without it
# survives a sync.
OPENCODE_GEN_MARKER="<!-- Generated by intelligence-sync. Do not edit manually. -->"

# Generate one slash command per synced skill.
# For each `<src>/<skill>/SKILL.md`, write `.opencode/commands/<skill>.md`
# with `description:` copied from the skill's `description` (YAML-escaped) and a body that tells the
# current agent to load the skill via the `skill` tool and pass `$ARGUMENTS`.
# Files marked with $OPENCODE_GEN_MARKER are removed before regeneration; any
# user-managed command without the marker is preserved. A user file that
# shares a name with a skill is overwritten by design — that 1:1 name
# binding is the whole point of the wrap.
sync_opencode_commands() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    local commands_dir="$output_dir/commands"
    mkdir -p "$commands_dir"

    # Marker-based cleanup: leave user-authored commands alone. One grep -l
    # finds every generated file; one rm removes them.
    local f
    local -a existing=() generated=()
    for f in "$commands_dir"/*.md; do
        [ -f "$f" ] && existing+=("$f")
    done
    if [ "${#existing[@]}" -gt 0 ]; then
        while IFS= read -r f; do
            [ -n "$f" ] && generated+=("$f")
        done < <(grep -lF "$OPENCODE_GEN_MARKER" "${existing[@]}" 2>/dev/null || true)
        [ "${#generated[@]}" -gt 0 ] && rm -f "${generated[@]}"
    fi

    local src d skill_name
    local -a skill_mds=()
    load_yaml_list "$config_file" "skills"
    local list="$IS_YAML_LIST"
    while IFS= read -r src; do
        [ -z "$src" ] && continue
        local dir="$repo_root/$src"
        [ -d "$dir" ] || continue
        for d in "$dir"/*/; do
            [ -d "$d" ] || continue
            [ -f "$d/SKILL.md" ] || continue
            skill_mds+=("${d%/}/SKILL.md")
        done
    done <<< "$list"

    local count=0
    if [ "${#skill_mds[@]}" -gt 0 ]; then
        local path description argument_hint out_file
        local -a out_files=()
        while IFS=$'\x1f' read -r path description argument_hint; do
            [ -n "$path" ] || continue
            skill_name="${path%/SKILL.md}"; skill_name="${skill_name##*/}"
            out_file="$commands_dir/$skill_name.md"
            yaml_dq_escape_var "$description"
            {
                echo "---"
                echo "description: \"$IS_YAML_ESCAPED\""
                echo "---"
                echo ""
                echo "$OPENCODE_GEN_MARKER"
                echo ""
                echo "Load and execute the \`$skill_name\` skill via the \`skill\` tool, then run it."
                echo ""
                if [ -n "$argument_hint" ]; then
                    echo "Pass these arguments to the skill: \$ARGUMENTS"
                    echo ""
                    echo "Argument hint from the source skill: \`$argument_hint\`"
                else
                    echo "Forward any provided arguments to the skill: \$ARGUMENTS"
                fi
            } > "$out_file"
            out_files+=("$out_file")
            count=$((count + 1))
            echo "  command: /$skill_name"
        done < <(frontmatter_index "description,argument-hint" "${skill_mds[@]}")
        [ "${#out_files[@]}" -gt 0 ] && finalize_output_files "${out_files[@]}"
    fi

    echo "  -> Commands: $count"
}

sync_opencode_agents() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    local agents_dir="$output_dir/agents"
    mkdir -p "$agents_dir"

    local src f
    local -a files=()
    load_yaml_list "$config_file" "agents"
    local list="$IS_YAML_LIST"
    while IFS= read -r src; do
        [ -z "$src" ] && continue
        local dir="$repo_root/$src"
        [ -d "$dir" ] || continue
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue
            files+=("$f")
        done
    done <<< "$list"

    local count=0
    if [ "${#files[@]}" -gt 0 ]; then
        load_model_tiers "$config_file" "opencode"

        local path tier access description name edit_perm bash_perm spec="" report="" LS=$'\x1e'
        while IFS=$'\x1f' read -r path tier access description; do
            [ -n "$path" ] || continue
            name="${path##*/}"; name="${name%.md}"
            resolve_model_var "$tier"

            # Map source `access:` to opencode permission keys.
            # `edit` gates write/edit/apply_patch; `bash` gates shell.
            case "$access" in
                readonly) edit_perm="deny";  bash_perm="deny"  ;;
                *)        edit_perm="allow"; bash_perm="allow" ;;
            esac

            local header
            yaml_dq_escape_var "$description"
            header="${LS}---"
            header+="${LS}description: \"$IS_YAML_ESCAPED\""
            header+="${LS}mode: subagent"
            if [ -n "$IS_MODEL" ]; then
                yaml_dq_escape_var "$IS_MODEL"
                header+="${LS}model: \"$IS_YAML_ESCAPED\""
            fi
            header+="${LS}permission:"
            header+="${LS}  edit: $edit_perm"
            header+="${LS}  bash: $bash_perm"
            header+="${LS}---"
            header+="${LS}"
            header+="${LS}<!-- Generated by intelligence-sync. Do not edit manually. -->"
            header+="${LS}"

            spec+="$path"$'\x1f'"$agents_dir/$name.md"$'\x1f'"strip"$'\x1f'"1"$'\x1f'"none"$'\x1f'"$header"$'\x1f\n'
            report+="  agent: $name.md"$'\n'
            count=$((count + 1))
        done < <(frontmatter_index "tier,access,description" "${files[@]}")

        emit_wrapped_bodies "$spec"
        printf '%s' "$report"
    fi

    echo "  -> Agents: $count"
}

sync_to_opencode() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    echo "=== opencode ==="

    # Adapter owns .opencode/agents/ entirely (so removed/renamed source
    # agents don't linger). Other .opencode/* files (e.g. user-managed
    # opencode.json) are left untouched. .opencode/commands/ is owned
    # marker-by-marker — see sync_opencode_commands.
    rm -rf "$output_dir/agents"
    mkdir -p "$output_dir/agents"

    sync_opencode_skills "$repo_root" "$config_file" "$output_dir"
    sync_opencode_commands "$repo_root" "$config_file" "$output_dir"
    sync_opencode_agents "$repo_root" "$config_file" "$output_dir"

    echo "  -> Rules: skipped (AGENTS.md carries always-on; opencode has no native path-scoped rules)"
}
