#!/bin/bash
# intelligence.lock — the resolved state, committed with the project.
#
# The lock is fully generated (npm's model): readers use the qmap parser from
# manifest.sh, writers rebuild the whole file from a row stream of entries.
# Columns: name, requested, url, path, resolved, sha — separated by the ASCII
# unit separator, NOT a tab: tab is IFS whitespace, so `read` would collapse
# an empty field (a rootless `path`) and shift every column after it.

LOCKFILE_VERSION=1
LOCK_SEP=$'\x1f'

# lock_validate <lock> [--metadata|--restore] [manifest] — read-only preflight. A subshell
# contains the fail-fast input guards so status can report a failed verdict too.
lock_validate() (
    local lock="$1" mode="${2---metadata}" manifest="${3:-}" count=0
    local kind name requested url path resolved sha line rows current
    local -x CLI_INPUT_CONTEXT=""
    [ "$#" -le 3 ] || die "internal: too many lock validation arguments"
    case "$mode" in
        --metadata|--restore) ;;
        *) die "internal: unknown lock validation mode '$mode'" ;;
    esac
    # The same tokenizer supplies ordinary lock rows and strict metadata. Buffer
    # before consumption: a failed parser must never yield a partial package set.
    rows="$(_qmap_read lock "$lock" packages '' '' "$LOCKFILE_VERSION")" || return $?
    current="$(bundled_engine_version)"
    while IFS="$LOCK_SEP" read -r kind name requested url path resolved sha line; do
        case "$kind" in
            V)
                [[ "$requested" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
                    || die "$lock has missing or invalid engine_version"
                continue
                ;;
            R) ;;
            *) die "internal: unexpected lock record '$kind'" ;;
        esac
        count=$((count + 1))
        CLI_INPUT_CONTEXT="$lock:$line: package $name, field name: "
        assert_valid_pkg_name "$name"
        CLI_INPUT_CONTEXT="$lock:$line: package $name, field url: "
        assert_safe_source_url "$url"
        CLI_INPUT_CONTEXT="$lock:$line: package $name, field resolved: "
        [ -n "$resolved" ] || die "locked restore: $name has a missing resolved ref"
        assert_safe_ref "$resolved"
        CLI_INPUT_CONTEXT="$lock:$line: package $name, field path: "
        assert_safe_package_path "$path"
        CLI_INPUT_CONTEXT="$lock:$line: package $name, field sha: "
        if [ -z "$sha" ]; then
            if [ "$url" = "$SYNC_PKG_URL" ] && [ "$path" = "$SYNC_PKG_PATH" ] \
                && [ "$resolved" = "v$current" ]; then
                continue
            fi
            # engine_version records the writer CLI, which can differ from the
            # preserved bundle pin after a same-major older CLI adds a package.
            # Versioned bundle metadata admits alignment/installed content only;
            # it must never authorize an unpinned cross-version acquisition.
            if [ "$mode" = "--metadata" ] && [ "$url" = "$SYNC_PKG_URL" ] \
                && [ "$path" = "$SYNC_PKG_PATH" ] && [[ "$resolved" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] \
                && [ "${resolved%%.*}" = "v${current%%.*}" ]; then
                echo "WARNING: $name at $resolved has no locked commit SHA; commit verification is unavailable for this development-bundle metadata" >&2
                continue
            fi
        fi
        [[ "$sha" =~ ^[0-9a-f]{40}$ || "$sha" =~ ^[0-9a-f]{64}$ ]] \
            || die "locked restore: $name has a missing or invalid commit SHA — restore a valid intelligence.lock"
    done <<< "$rows"
    if [ "$count" -eq 0 ] && [ -n "$manifest" ] && [ -n "$(qmap_keys "$manifest" packages)" ]; then
        die "$lock: packages is empty but the manifest declares packages — restore their recorded identities"
    fi
)

# top_scalar <file> <key> — one top-level scalar through the shared tokenizer.
top_scalar() {
    _qmap_read top "$1" '' "$2"
}

# lock_to_tsv <lock> — every locked package as one row.
lock_to_tsv() {
    _qmap_read rows "$1" packages
}

# lock_write_from_tsv <lock> <tsv-file> — rebuild the lock. Entries are
# written in the TSV's order; callers keep it stable (manifest order).
lock_write_from_tsv() {
    local lock="$1" tsv="$2"
    local tmp="$lock.cli.tmp"
    {
        echo "# Generated by the intelligence CLI. Do not edit."
        echo "lockfile_version: $LOCKFILE_VERSION"
        echo "engine_version: \"$(bundled_engine_version)\""
        echo "packages:"
        # Values reach a double-quoted YAML scalar: a `"` or `\` in any of
        # them (registry-supplied url/path included) must be escaped, or it
        # would break or alias the neighbouring field.
        awk -F"$LOCK_SEP" '
            function esc(s,    i, c, out) {
                out = ""
                for (i = 1; i <= length(s); i++) {
                    c = substr(s, i, 1)
                    if (c == "\\" || c == "\"") out = out "\\"
                    out = out c
                }
                return out
            }
            NF >= 6 {
                print "  \"" esc($1) "\":"
                if ($2 != "") print "    requested: \"" esc($2) "\""
                print "    url: \"" esc($3) "\""
                if ($4 != "") print "    path: \"" esc($4) "\""
                if ($5 != "") print "    resolved: \"" esc($5) "\""
                print "    sha: \"" esc($6) "\""
            }
        ' "$tsv"
    } > "$tmp"
    mv "$tmp" "$lock"
}

# lock_upsert <lock> <name> <requested> <url> <path> <resolved> <sha>
# Replace-or-append one entry, keeping the others.
lock_upsert() {
    local lock="$1" name="$2" requested="$3" url="$4" path="$5" resolved="$6" sha="$7"
    local tsv
    tsv="$(mktemp -t intelligence-lock-XXXXXX 2>/dev/null || mktemp)"
    {
        lock_to_tsv "$lock" | awk -F"$LOCK_SEP" -v n="$name" '$1 != n'
        printf '%s\037%s\037%s\037%s\037%s\037%s\n' \
            "$name" "$requested" "$url" "$path" "$resolved" "$sha"
    } > "$tsv"
    lock_write_from_tsv "$lock" "$tsv"
    rm -f "$tsv"
}

# lock_remove <lock> <name>
lock_remove() {
    local lock="$1" name="$2"
    [ -f "$lock" ] || return 0
    local tsv
    tsv="$(mktemp -t intelligence-lock-XXXXXX 2>/dev/null || mktemp)"
    lock_to_tsv "$lock" | awk -F"$LOCK_SEP" -v n="$name" '$1 != n' > "$tsv"
    if [ -s "$tsv" ]; then
        lock_write_from_tsv "$lock" "$tsv"
    else
        rm -f "$lock"
    fi
    rm -f "$tsv"
}
