#!/bin/bash
# intelligence.lock — the resolved state, committed with the project.
#
# The lock is fully generated (npm's model): readers use the qmap parser from
# manifest.sh, writers rebuild the whole file from a row stream of entries.
# Columns: name, requested, url, path, resolved, sha — separated by the ASCII
# unit separator, NOT a tab: tab is IFS whitespace, so `read` would collapse
# an empty field (a rootless `path`) and shift every column after it.

LOCKFILE_VERSION=1
LOCK_SEP=$'\x1f'

# top_scalar <file> <key> — one top-level scalar (`key: "value"`), quotes and
# trailing comment stripped. The declared exception to "no new parsing": the
# engine's read_schema_version is hardwired to its own key.
top_scalar() {
    [ -f "$1" ] || return 0
    awk -v key="$2" '
        { sub(/\r$/, "") }
        $0 ~ "^" key ":" {
            v = substr($0, length(key) + 2)
            sub(/^[ \t]+/, "", v)
            if (v ~ /^"/) { v = substr(v, 2); q = index(v, "\""); if (q > 0) v = substr(v, 1, q - 1) }
            else { sub(/[ \t]+#.*$/, "", v); sub(/[ \t]+$/, "", v) }
            print v
            exit
        }
    ' "$1"
}

# lock_to_tsv <lock> — every locked package as one row.
lock_to_tsv() {
    local lock="$1" name
    [ -f "$lock" ] || return 0
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        printf '%s\037%s\037%s\037%s\037%s\037%s\n' \
            "$name" \
            "$(qmap_field "$lock" "packages" "$name" "requested")" \
            "$(qmap_field "$lock" "packages" "$name" "url")" \
            "$(qmap_field "$lock" "packages" "$name" "path")" \
            "$(qmap_field "$lock" "packages" "$name" "resolved")" \
            "$(qmap_field "$lock" "packages" "$name" "sha")"
    done < <(qmap_keys "$lock" "packages")
}

# lock_write_from_tsv <lock> <tsv-file> — rebuild the lock. Entries are
# written in the TSV's order; callers keep it stable (manifest order).
lock_write_from_tsv() {
    local lock="$1" tsv="$2"
    local tmp="$lock.cli.tmp"
    {
        echo "# Generated by the intelligence CLI. Do not edit."
        echo "lockfile_version: $LOCKFILE_VERSION"
        echo "engine_version: \"$(bundled_engine_version)\""
        echo "packages:"
        # Values reach a double-quoted YAML scalar: a `"` or `\` in any of
        # them (registry-supplied url/path included) must be escaped, or it
        # would break or alias the neighbouring field.
        awk -F"$LOCK_SEP" '
            function esc(s) { gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); return s }
            NF >= 6 {
                print "  \"" esc($1) "\":"
                if ($2 != "") print "    requested: \"" esc($2) "\""
                print "    url: \"" esc($3) "\""
                if ($4 != "") print "    path: \"" esc($4) "\""
                if ($5 != "") print "    resolved: \"" esc($5) "\""
                print "    sha: \"" esc($6) "\""
            }
        ' "$tsv"
    } > "$tmp"
    mv "$tmp" "$lock"
}

# lock_upsert <lock> <name> <requested> <url> <path> <resolved> <sha>
# Replace-or-append one entry, keeping the others.
lock_upsert() {
    local lock="$1" name="$2" requested="$3" url="$4" path="$5" resolved="$6" sha="$7"
    local tsv
    tsv="$(mktemp -t intelligence-lock-XXXXXX 2>/dev/null || mktemp)"
    {
        lock_to_tsv "$lock" | awk -F"$LOCK_SEP" -v n="$name" '$1 != n'
        printf '%s\037%s\037%s\037%s\037%s\037%s\n' \
            "$name" "$requested" "$url" "$path" "$resolved" "$sha"
    } > "$tsv"
    lock_write_from_tsv "$lock" "$tsv"
    rm -f "$tsv"
}

# lock_remove <lock> <name>
lock_remove() {
    local lock="$1" name="$2"
    [ -f "$lock" ] || return 0
    local tsv
    tsv="$(mktemp -t intelligence-lock-XXXXXX 2>/dev/null || mktemp)"
    lock_to_tsv "$lock" | awk -F"$LOCK_SEP" -v n="$name" '$1 != n' > "$tsv"
    if [ -s "$tsv" ]; then
        lock_write_from_tsv "$lock" "$tsv"
    else
        rm -f "$lock"
    fi
    rm -f "$tsv"
}
